### ISSUE TITLE
Image link needs to be adjusted

### ISSUE THREAD

**Issue by dwiehoff** [learn-co-curriculum/javascript-callbacks#7]
![image](http://deggler.com/wp-content/uploads/2016/06/pexels-photo-87306-medium.jpeg)

The image link is seemingly no longer available and cannot be displayed. This is the image that should be showing.

**Comment by gj** [comment]
Fixed in 1be10eff9d1b88548e3c3eeae3d5543d6bde539c.

Thanks @dwiehoff !
